[build]
builder = "nixpacks"

[[build.nixpacksPlan.phases.setup]]
nixPkgs = ["nodejs_20", "go_1_24"]

[[build.nixpacksPlan.phases.install]]
cmds = ["npm install"]

[[build.nixpacksPlan.phases.build]]
cmds = [
  "npm run build",
  "go build -o app ./cmd/api"
]

[deploy]
startCommand = "./app"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
